version: "3"
services:
  backend:
    build: ./expressjs-and-rest-Varun3311  # Path to your backend folder with Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend  # Path to your frontend folder with Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:5000  # Backend service URL for frontend
    depends_on:
      - backend  # Ensure backend is up before frontend starts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
